### ISSUE TITLE
Basic checks on student patchset submissions

### ISSUE THREAD

**Issue by theyoyojo** [underground-software/singularity#58]
Verify:
- correct # of patches
- correct files modified
- cover letter exists
- DCO correct
- relevant due date in future

**Comment by charliemirabile** [comment]
as an indication of whether the patches were hand edited / only partially regenerated we can apply the patches and then re format them and the output should match exactly. Not sure if them not matching would be an immediate fail, but it is suspicious since the patches might contain other issues if not generated according to the directions.
